export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_PROFILE = "CLEAR_PROFILE";

export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const GET_CATEGORY = "GET_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const CATEGORY_ERROR = "CATEGORY_ERROR";

export const GET_ATTRACTIONS = "GET_ATTRACTIONS";
export const ADD_ATTRACTION = "ADD_ATTRACTION";
export const GET_ATTRACTION = "GET_ATTRACTION";
export const DELETE_ATTRACTION = "DELETE_ATTRACTION";
export const UPDATE_ATTRACTION = "UPDATE_ATTRACTION";
export const ATTRACTION_ERROR = "ATTRACTION_ERROR";

export const GET_GALLERIES = "GET_GALLERIES";
export const ADD_GALLERY = "ADD_GALLERY";
export const DELETE_GALLERY = "REMOVE_GALLERY";
export const GALLERY_ERROR = "GALLER_ERROR";
